[platformio]
src_dir = main

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs =
    components/utils
    components/drivers
    components/managers
    components/services
lib_ldf_mode = deep+
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 4MB
board_build.variants_dir = variants
build_flags =
    -std=gnu++17
    -Icomponents/config/include
    -Icomponents/utils/include
    -Icomponents/drivers/buzzer/include
    -Icomponents/drivers/flow_sensor/include
    -Icomponents/drivers/pressure_sensor/include
    -Icomponents/drivers/relay/include
    -Icomponents/drivers/tds_sensor/include
    -Icomponents/managers/device_manager/include
    -Icomponents/managers/network_manager/include
    -Icomponents/managers/sensor_manager/include
    -Icomponents/services/logger/include
    -Icomponents/services/mqtt/include
    -Icomponents/services/wifi/include
lib_deps =
    bblanchon/ArduinoJson@^7.0.4
    knolleary/PubSubClient@^2.8
